import {WIDGET_HEIGHT, WIDGET_BORDER_RADIUS} from "./myWidget";
import {
	WIDGET_BUTTON_BORDER_RADIUS,
	WIDGET_BUTTON_SIZE
} from "./myWidgetButton";

export {
	WIDGET_HEIGHT,
	WIDGET_BORDER_RADIUS,
	WIDGET_BUTTON_BORDER_RADIUS,
	WIDGET_BUTTON_SIZE
};
